package tools

import (
	"context"
	"fmt"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/shivanshkc/workspacemcp/pkg/workspace"
)

// ReadDocumentAsMarkdownInput holds the input parameters required by the ReadDocumentAsMarkdown tool.
type ReadDocumentAsMarkdownInput struct {
	DocID  string
	Limit  int
	Offset int
}

// ReadDocumentAsMarkdownOutput holds the output generated by the ReadDocumentAsMarkdown tool.
type ReadDocumentAsMarkdownOutput struct {
	Content string
}

// Handler encapsulates all tool handler methods.
type Handler struct {
	workspaceClient *workspace.Client
}

// NewHandler instantiates a new Handler instance.
func NewHandler(wClient *workspace.Client) (*Handler, error) {
	return &Handler{workspaceClient: wClient}, nil
}

// GetDocumentSizeInput holds the input parameters required by the GetDocumentSize tool.
type GetDocumentSizeInput struct {
	DocID string
}

// GetDocumentSizeOutput holds the output generated by the GetDocumentSize tool.
type GetDocumentSizeOutput struct {
	CharCount int
}

// GetDocumentSize returns the character count of a Google Doc as exported to markdown.
func (h *Handler) GetDocumentSize(
	ctx context.Context, req *mcp.CallToolRequest, input GetDocumentSizeInput,
) (*mcp.CallToolResult, GetDocumentSizeOutput, error) {
	size, err := h.workspaceClient.GetDocumentSize(ctx, input.DocID)
	if err != nil {
		return nil, GetDocumentSizeOutput{}, fmt.Errorf("failed to get document size: %w", err)
	}

	content := fmt.Sprintf("characters: %d", size.CharCount)
	return &mcp.CallToolResult{
		Content: []mcp.Content{&mcp.TextContent{Text: content}},
	}, GetDocumentSizeOutput{CharCount: size.CharCount}, nil
}

// ReadDocumentAsMarkdown fetches the specified Google Doc and returns its content as markdown.
// Use limit and offset to page through large documents; defaults are 20000 chars and 0 respectively.
func (h *Handler) ReadDocumentAsMarkdown(
	ctx context.Context, req *mcp.CallToolRequest, input ReadDocumentAsMarkdownInput,
) (*mcp.CallToolResult, ReadDocumentAsMarkdownOutput, error) {
	markdown, err := h.workspaceClient.ReadDocumentAsMarkdown(ctx, input.DocID)
	if err != nil {
		return nil, ReadDocumentAsMarkdownOutput{}, fmt.Errorf("failed to read document: %w", err)
	}

	if input.Offset < len(markdown) {
		markdown = markdown[input.Offset:]
	} else {
		markdown = ""
	}

	if input.Limit > 0 && input.Limit < len(markdown) {
		markdown = markdown[:input.Limit]
	}

	content := markdown
	return &mcp.CallToolResult{
		Content: []mcp.Content{&mcp.TextContent{Text: content}},
	}, ReadDocumentAsMarkdownOutput{Content: content}, nil
}
