package tools

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/shivanshkc/workspacemcp/pkg/workspace"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// ReadDocumentAsMarkdownInput holds the input parameters required by the ReadDocumentAsMarkdown tool.
type ReadDocumentAsMarkdownInput struct {
	DocID  string
	Limit  int
	Offset int
}

// ReadDocumentAsMarkdownOutput holds the output generated by the ReadDocumentAsMarkdown tool.
type ReadDocumentAsMarkdownOutput struct {
	Content string
}

// Handler encapsulates all tool handler methods.
type Handler struct {
	workspaceClient *workspace.Client
}

// NewHandler instantiates a new Handler instance.
func NewHandler(wClient *workspace.Client) (*Handler, error) {
	return &Handler{workspaceClient: wClient}, nil
}

// GetDocumentSizeInput holds the input parameters required by the GetDocumentSize tool.
type GetDocumentSizeInput struct {
	DocID string
}

// GetDocumentSizeOutput holds the output generated by the GetDocumentSize tool.
type GetDocumentSizeOutput struct {
	CharCount int
}

// GetDocumentSize returns the character count of a Google Doc as exported to markdown.
func (h *Handler) GetDocumentSize(
	ctx context.Context, req *mcp.CallToolRequest, input GetDocumentSizeInput,
) (*mcp.CallToolResult, GetDocumentSizeOutput, error) {
	size, err := h.workspaceClient.GetDocumentSize(ctx, input.DocID)
	if err != nil {
		return nil, GetDocumentSizeOutput{}, fmt.Errorf("failed to get document size: %w", err)
	}

	content := fmt.Sprintf("characters: %d", size.CharCount)
	return &mcp.CallToolResult{
		Content: []mcp.Content{&mcp.TextContent{Text: content}},
	}, GetDocumentSizeOutput{CharCount: size.CharCount}, nil
}

// ListSheetsInput holds the input parameters required by the ListSheets tool.
type ListSheetsInput struct {
	SpreadsheetID string
}

// ListSheetsOutput holds the output generated by the ListSheets tool.
type ListSheetsOutput struct {
	Sheets []string `json:"sheets"`
}

// ListSheets returns the names of all sheets in a Google Spreadsheet.
func (h *Handler) ListSheets(
	ctx context.Context, req *mcp.CallToolRequest, input ListSheetsInput,
) (*mcp.CallToolResult, ListSheetsOutput, error) {
	sheets, err := h.workspaceClient.ListSheets(ctx, input.SpreadsheetID)
	if err != nil {
		return nil, ListSheetsOutput{}, fmt.Errorf("failed to list sheets: %w", err)
	}

	content, _ := json.Marshal(sheets)
	out := ListSheetsOutput{Sheets: sheets}
	return &mcp.CallToolResult{
		Content: []mcp.Content{&mcp.TextContent{Text: string(content)}},
	}, out, nil
}

// GetSheetSizeInput holds the input parameters required by the GetSheetSize tool.
type GetSheetSizeInput struct {
	SpreadsheetID string
	SheetName     string
}

// GetSheetSizeOutput holds the output generated by the GetSheetSize tool.
type GetSheetSizeOutput struct {
	RowCount  int    `json:"rowCount"`
	ColCount  int    `json:"colCount"`
	DataRange string `json:"dataRange"`
}

// GetSheetSize returns the extent of actual data in a sheet.
func (h *Handler) GetSheetSize(
	ctx context.Context, req *mcp.CallToolRequest, input GetSheetSizeInput,
) (*mcp.CallToolResult, GetSheetSizeOutput, error) {
	size, err := h.workspaceClient.GetSheetSize(ctx, input.SpreadsheetID, input.SheetName)
	if err != nil {
		return nil, GetSheetSizeOutput{}, fmt.Errorf("failed to get sheet size: %w", err)
	}

	out := GetSheetSizeOutput{RowCount: size.RowCount, ColCount: size.ColCount, DataRange: size.DataRange}
	content, _ := json.Marshal(out)
	return &mcp.CallToolResult{
		Content: []mcp.Content{&mcp.TextContent{Text: string(content)}},
	}, out, nil
}

// ReadSheetInput holds the input parameters required by the ReadSheet tool.
type ReadSheetInput struct {
	SpreadsheetID string
	SheetName     string
	Range         string
}

// ReadSheetOutput holds the output generated by the ReadSheet tool.
type ReadSheetOutput struct {
	Rows [][]any `json:"rows"`
}

// ReadSheet reads cells from a sheet and returns them as a 2D array.
func (h *Handler) ReadSheet(
	ctx context.Context, req *mcp.CallToolRequest, input ReadSheetInput,
) (*mcp.CallToolResult, ReadSheetOutput, error) {
	rows, err := h.workspaceClient.ReadSheet(ctx, input.SpreadsheetID, input.SheetName, input.Range)
	if err != nil {
		return nil, ReadSheetOutput{}, fmt.Errorf("failed to read sheet: %w", err)
	}

	out := ReadSheetOutput{Rows: rows}
	content, _ := json.Marshal(rows)
	return &mcp.CallToolResult{
		Content: []mcp.Content{&mcp.TextContent{Text: string(content)}},
	}, out, nil
}

// ReadDocumentAsMarkdown fetches the specified Google Doc and returns its content as markdown.
// Use limit and offset to page through large documents; defaults are 20000 chars and 0 respectively.
func (h *Handler) ReadDocumentAsMarkdown(
	ctx context.Context, req *mcp.CallToolRequest, input ReadDocumentAsMarkdownInput,
) (*mcp.CallToolResult, ReadDocumentAsMarkdownOutput, error) {
	markdown, err := h.workspaceClient.ReadDocumentAsMarkdown(ctx, input.DocID)
	if err != nil {
		return nil, ReadDocumentAsMarkdownOutput{}, fmt.Errorf("failed to read document: %w", err)
	}

	if input.Offset < len(markdown) {
		markdown = markdown[input.Offset:]
	} else {
		markdown = ""
	}

	if input.Limit > 0 && input.Limit < len(markdown) {
		markdown = markdown[:input.Limit]
	}

	content := markdown
	return &mcp.CallToolResult{
		Content: []mcp.Content{&mcp.TextContent{Text: content}},
	}, ReadDocumentAsMarkdownOutput{Content: content}, nil
}
